name: Scan for Evil Packages

on:
  repository_dispatch:
    types: [trigger-from-scanmaestro]
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Scan for Evil Packages
        uses: UKHomeOfficeForms/hof-temp-gha-collection/.github/actions/scan-for-evil-packages@v1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}